Remove condition for new enum values
Now condition not implemented and raised error

```
sql = schema_editor.sql_alter_enum % {
KeyError: 'condition'
```

This happens because no condition for formating string

```
ALTER TYPE %(enum_type)s ADD VALUE %(value)s %(condition)s' % {'enum_type': self.db_type, 'value': '%s'}
```

https://github.com/ashleywaite/django-more/blob/master/django_enum/operations.py#L319-L321